language: go

sudo: false

go:
  - "1.4"
  - "1.5"
  - "1.7"
  - "1.8"
  - "1.9"
  - master

before_install:
  - go get github.com/golang/lint/golint
  - go get -t ./...

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -service=travis-ci
  - go test -v ./...
